/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#0b1c30',
        'inverse-surface': '#2d3133',
        'secondary': '#0058be',
        'on-primary-fixed-variant': '#3f465c',
        'on-background': '#191c1e',
        'on-secondary-fixed': '#001a42',
        'on-tertiary': '#ffffff',
        'error-container': '#ffdad6',
        'surface-container-high': '#e6e8ea',
        'on-surface-variant': '#45464d',
        'inverse-on-surface': '#eff1f3',
        'on-tertiary-fixed': '#0b1c30',
        'secondary-container': '#2170e4',
        'on-surface': '#191c1e',
        'tertiary-fixed-dim': '#b7c8e1',
        'primary': '#000000',
        'primary-container': '#131b2e',
        'surface-container': '#eceef0',
        'tertiary': '#000000',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'on-primary-container': '#7c839b',
        'inverse-primary': '#bec6e0',
        'on-tertiary-fixed-variant': '#38485d',
        'surface-dim': '#d8dadc',
        'outline': '#76777d',
        'surface-bright': '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'on-primary-fixed': '#131b2e',
        'secondary-fixed': '#d8e2ff',
        'tertiary-fixed': '#d3e4fe',
        'on-secondary': '#ffffff',
        'surface': '#f7f9fb',
        'on-tertiary-container': '#75859d',
        'on-secondary-container': '#fefcff',
        'primary-fixed-dim': '#bec6e0',
        'on-error-container': '#93000a',
        'background': '#f7f9fb',
        'surface-container-highest': '#e0e3e5',
        'outline-variant': '#c6c6cd',
        'error': '#ba1a1a',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed-variant': '#004395',
        'primary-fixed': '#dae2fd',
        'on-primary': '#ffffff',
        'surface-tint': '#565e74',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-md': '16px',
        'container-max': '1440px',
        'stack-sm': '8px',
        'margin-page': '32px',
        'panel-gap': '16px',
        'gutter': '24px',
        'stack-lg': '24px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'code-sm': ['JetBrains Mono', 'monospace'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'display-lg': ['30px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'code-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
